<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <UserSecretsId>4147d4bf-905d-434c-8f04-c26c0f755d30</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <TrimmerRootAssembly Include="BlazorOcticons" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\CNAME">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BlazorOcticons" Version="1.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="9.0.0" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="wwwroot\.nojekyll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
